rabbit:
  image: "rabbitmq:management-alpine"
  hostname: "rabbit"
  environment:
    RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    RABBITMQ_DEFAULT_USER: "rabbitmq"
    RABBITMQ_DEFAULT_PASS: "rabbitmq"
    RABBITMQ_DEFAULT_VHOST: "/"
  ports:
    - "15672:15672"
    - "5672:5672"
  labels:
    NAME: "rabbitmq"
federation_importer:
    image: "federation_importer:latest"
    environment:
        ENTITY_URL: "http://metadata.ukfederation.org.uk/ukfederation-metadata.xml"
        QUEUE_CONN: "amqp://rabbitmq:rabbitmq@rabbit:5672/"
    links:
        - rabbit
        - mongodb
export_worker:
    image: "export_worker:latest"
    environment:
        QUEUE_CONN: "amqp://rabbitmq:rabbitmq@rabbit:5672/"
    links:
        - rabbit
        - mongodb
webui:
    image: "webui:latest"
    expose:
        - "80"
webapi:
    image: "webapi:latest"
    expose:
        - "80"
    environment:
        QUEUE_CONN: "amqp://rabbitmq:rabbitmq@rabbit:5672/"
        MONGO_CONN: "mongodb"
    links:
        - rabbit
        - mongodb
mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
reverse_proxy:
    image: reverse_proxy:latest
    ports:
        - 8080:8080
    links:
        - webui
        - webapi
