rabbit:
  image: "rabbitmq:management-alpine"
  hostname: "rabbit"
  environment:
    RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    RABBITMQ_DEFAULT_USER: "rabbitmq"
    RABBITMQ_DEFAULT_PASS: "rabbitmq"
    RABBITMQ_DEFAULT_VHOST: "/"
  ports:
    - "15672:15672"
    - "5672:5672"
  labels:
    NAME: "rabbitmq"
  # volumes:
    # - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
    #- "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
    #- "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.e
federation_importer:
    image: "federation_importer:latest"
    environment:
        ENTITY_URL: "http://metadata.ukfederation.org.uk/ukfederation-metadata.xml"
        QUEUE_CONN: "amqp://rabbitmq:rabbitmq@rabbit:5672/"
    links:
        - rabbit
entity_importer_worker:
    image: "entity_importer_worker:latest"
    environment:
        QUEUE_CONN: "amqp://rabbitmq:rabbitmq@rabbit:5672/"
    links:
        - rabbit
