# build
FROM golang:1.8-alpine AS build-env
RUN apk update && apk upgrade && apk add --no-cache bash git openssh
RUN mkdir -p /go/src/github.com/markwallsgrove/saml_federation_proxy
WORKDIR /go/src/github.com/markwallsgrove/saml_federation_proxy
COPY . .
WORKDIR entity_importer_worker
RUN go-wrapper download
RUN go build -o /bin/entity_importer_worker main.go

# resulting image
FROM scratch
COPY --from=build-env /bin/entity_importer_worker /bin/
CMD ["/bin/entity_importer_worker"]
